Feat: Create shader system
FppEpitech/R-Type pull request #127
Opened 2024-10-06 16:15 UTC by Peralban

Create shader initialisation and display.
At the beginning, we need a Settings.json file in Game/Config
![image](https://github.com/user-attachments/assets/e8970976-f037-4f89-b253-728b67da0feb)

The whole shader will be saved in a map, and if "current" changes, the shader will be applied with the function I created.

Example of shader utilisation:

![image](https://github.com/user-attachments/assets/6ad254ea-c09e-421a-991d-4fffe97d875a)
![image](https://github.com/user-attachments/assets/df112e24-ed2a-4522-b169-861250550d83)

---

![image](https://github.com/user-attachments/assets/f68a5c78-0481-426b-b5de-f721a3179a6b)
![image](https://github.com/user-attachments/assets/5d820db6-9d2a-44be-9e16-e80a5943fbb0)

---

![image](https://github.com/user-attachments/assets/ff869b3c-2470-41b3-af7a-5960a3eaae44)
![image](https://github.com/user-attachments/assets/63814394-e5c7-4601-9dc8-6e3d8af7202d)

---

![image](https://github.com/user-attachments/assets/b86e57c2-e222-4d4a-8c6d-450e716ff189)
![image](https://github.com/user-attachments/assets/f8c3502c-5974-4ef5-ac96-f027d0874fe6)

2024-10-06 16:24 UTC, Thomaltarix requested changes
Some little changes about comments or file names

2024-10-06 16:24 UTC, Thomaltarix commented on Game/Assets/player.gif
The file is already existing as `Game/Assets/players.gif`

2024-10-06 16:24 UTC, Thomaltarix commented on Game/Config/Settings.json
I think you should rename the file `ShaderSettings.json` or putting it into a sub-folder Shaders in the Config one

2024-10-06 16:24 UTC, Thomaltarix commented on GraphicLibrary/Src/GraphicLib.hpp
> +        bool _isShaderReady();
A little comment would be nice 👍

2024-10-06 16:29 UTC, Peralban commented on Game/Config/Settings.json
No, in Settings, there will be a multitude of settings, including quality settings. Therefore, we do not need to divide all our JSON files, as we can combine all the settings into a single file.

2024-10-06 16:30 UTC, mathieurobert1 requested changes

2024-10-06 16:30 UTC, mathieurobert1 commented on Engine/Client/Src/InitShader/InitShader.hpp
> +    };
Add comments to this

2024-10-06 16:30 UTC, mathieurobert1 commented on Game/Assets/player.gif
Yep

2024-10-07 09:05 UTC, mathieurobert1 approved these changes

2024-10-07 09:08 UTC, Thomaltarix approved these changes

2024-10-07 09:08 UTC, merged