FEAT: user system with sqlite
FppEpitech/R-Type pull request #187
Opened 2024-10-21 11:26 UTC by theophile-jr

Install sqlite3 with vcpkg

2024-10-22 16:57 UTC, mathieurobert1 requested changes

2024-10-22 16:57 UTC, mathieurobert1 commented on Network/User/User.hpp
> +        sqlite3 *_db = nullptr; // Database.
Please use std::shared_ptr<sqlite3>

2024-10-23 10:14 UTC, mathieurobert1 requested changes
Check your shared pointer

2024-10-23 10:14 UTC, mathieurobert1 commented on Network/User/User.cpp
> +    _db = std::shared_ptr<sqlite3>(db, sqlite3_close);
Check if _db is not null after that.

2024-10-23 11:39 UTC, mathieurobert1 approved these changes

2024-10-23 11:42 UTC, Peralban approved these changes

2024-10-23 11:45 UTC, merged