Feat: Create an abstract for the buttons creation
FppEpitech/R-Type pull request #195
Opened 2024-10-21 17:23 UTC by Thomaltarix

I created an abstract class for all the button init systems.
It involves the update of those buttons systems and the update of the systems cmake.

2024-10-21 17:29 UTC, Peralban approved these changes

2024-10-21 17:31 UTC, Peralban approved these changes

2024-10-22 07:12 UTC, mathieurobert1 requested changes
Just a method that isn't commented.

2024-10-22 07:12 UTC, mathieurobert1 commented on R-TypeGame/Systems/Menus/Buttons/IpTextBox/IpTextBoxInitSystem.hpp
> +        void _initButton(ECS::Registry& reg, int idxPacketEntities);
Comment this method

2024-10-22 09:26 UTC, Thomaltarix commented on R-TypeGame/Systems/Menus/Buttons/IpTextBox/IpTextBoxInitSystem.hpp
> +        void _initButton(ECS::Registry& reg, int idxPacketEntities);
Done

2024-10-22 09:39 UTC, Peralban approved these changes

2024-10-22 11:29 UTC, mathieurobert1 approved these changes

2024-10-22 11:37 UTC, merged