REFACTOR: user system
FppEpitech/R-Type pull request #228
Opened 2024-10-23 16:01 UTC by theophile-jr

* User is now Database as it contains more data
* Passwords are hashed in db
* Better error handling
Working on adding the scores (leaderboard) and daltonian and resolution in the db.

2024-10-26 14:41 UTC, Peralban approved these changes

2024-10-26 15:18 UTC, mathieurobert1 requested changes
Some changes.
And also, why did you use so many raw pointers ? Is'nt it possible to pass them into shared_ptr ?

2024-10-26 15:18 UTC, mathieurobert1 commented on Engine/Server/Src/main.cpp
> +// #include "Users.hpp"
You know.

2024-10-26 15:18 UTC, mathieurobert1 commented on Network/Database/Database.hpp
> +        // bool createTables();
Remove this if it's useless.

2024-10-26 15:34 UTC, mathieurobert1 approved these changes

2024-10-27 10:38 UTC, mathieurobert1 submitted a review, later dismissed
Thanks for shared ptr

2024-10-27 10:38 UTC, mathieurobert1 commented on Engine/Server/Src/main.cpp
> +#include "Users.hpp"
Why did you need that on the main ?

2024-10-27 17:30 UTC, Peralban approved these changes

2024-10-28 12:15 UTC, Peralban approved these changes

2024-10-28 12:18 UTC, mathieurobert1 approved these changes

2024-10-28 12:24 UTC, merged