FEAT: Create RollBAck system and Link ABI to UpdateShootSystem
FppEpitech/R-Type pull request #259
Opened 2024-10-29 20:32 UTC by AxelF44

I've Create the RollBack system:

I've add a MessageType (AssignToken) and their associated function to send her idxENtity to the client, so that it can procces the key

And I've link the Shootsystem with ABi so now the Player can shoot.

2024-10-29 21:41 UTC, mathieurobert1 requested changes

2024-10-29 21:41 UTC, mathieurobert1 commented on Engine/Client/Src/Application/Application.cpp
> +        //ABINetwork::sendPacketKey(_client, key);
Can you uncomment that please ? :smile: 
We want to send the key to the server.

2024-10-29 21:41 UTC, mathieurobert1 commented on Engine/Client/Src/Application/Application.hpp
> +        int               _idxEntity;   // IdxEntity
```suggestion
        int               _idxEntityPlayer;   // index of the client's player component

```

2024-10-30 09:49 UTC, mathieurobert1 approved these changes

2024-10-30 10:05 UTC, Thomaltarix approved these changes
Nothing to say, great 👍

2024-10-30 10:08 UTC, merged