FEAT: Implement the back and log out buttons
FppEpitech/R-Type pull request #263
Opened 2024-10-30 16:42 UTC by Thomaltarix

I implemented all the needed back buttons for now.

These buttons basically switch scene to the right scene

2024-10-30 17:10 UTC, Peralban approved these changes

2024-10-30 19:13 UTC, Peralban requested changes

2024-10-30 19:13 UTC, Peralban commented on R-TypeGame/Systems/CMakeLists.txt
Blank Line

2024-10-30 20:02 UTC, mathieurobert1 approved these changes

2024-10-31 01:01 UTC, Peralban approved these changes

2024-10-31 07:10 UTC, merged