Create the main class of client
FppEpitech/R-Type pull request #46
Opened 2024-09-25 15:53 UTC by Thomaltarix

I created the main class of the client which is the Application.
The application will need to handle the network, the scene manager and the ECS.
For now, it doesn't handle much things because they're not implemented

2024-09-25 15:54 UTC, Peralban approved these changes

2024-09-25 16:06 UTC, Peralban requested changes
Can you make a folder Application and place your class inside ?

2024-09-25 17:56 UTC, mathieurobert1 approved these changes

2024-09-26 08:19 UTC, Thomaltarix commented on Client/src/Application.hpp
> +        void Run();
Done

2024-09-26 11:44 UTC, Peralban approved these changes

2024-09-26 11:47 UTC, merged