Create contributing file
FppEpitech/R-Type pull request #6
Opened 2024-09-17 14:25 UTC by Peralban

To obtains more details, please see:
- #5

2024-09-17 14:37 UTC, Thomaltarix approved these changes

2024-09-17 15:01 UTC, mathieurobert1 requested changes
Can you please add a section for issues norms ?

2024-09-17 16:51 UTC, mathieurobert1 approved these changes
Perfect

2024-09-17 16:58 UTC, Thomaltarix approved these changes

2024-09-17 17:02 UTC, theophile-jr approved these changes

2024-09-18 07:29 UTC, AxelF44 approved these changes

2024-09-18 12:50 UTC, merged